### ISSUE TITLE
Als GIDS wil ik dat mijn besturingsinput wordt gestuurd met een JSON object, zodat de auto op afstand wordt bestuurd.

### ISSUE THREAD

**Issue by Nelio-J** [faroeq33/TLE1#3]
[Kijk naar server.js https://github.com/Ddvos/ip-car/tree/master/webapp/src](https://github.com/Ddvos/ip-car/blob/master/webapp/server.js)

https://miro.com/app/board/uXjVNbJUoGQ=/

**Comment by faroeq33** [comment]
Wegens tijd tekort is deze story geschrapt
