### ISSUE TITLE
Hosting en live zetten van website via DigitalOcean met huidige versie.

### ISSUE THREAD

**Issue by JaapMoerkerk** [faroeq33/TLE1#59]

**Comment by faroeq33** [comment]
Faroeq & Jaap gaan samenwerken aan het live zetten van de website, 9 januari 2024

**Comment by roel204** [comment]
Van Siteground naar DigitalOcean verrandert.

**Comment by faroeq33** [comment]
Het domein moet nog naar een mooie domein worden gezet, het staat nu nog op de gegenereerde url.
